name: C/C++ CI

on:
  push:
    tags:
      - "v*"  # Runs when you push a tag like "v1.0", "v2.0.1", etc.

permissions:
  contents: write  # Allows creating releases

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential make g++ libsdl2-dev libfuse-dev
    - name: Compile project
      run: make app
      
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-binaries
        path: gbmu-x86_64.AppImage

  release:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: release-binaries
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: gbmu-x86_64.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
